<?php

namespace App\Filament\Resources\FeedbackResource\Pages;

use App\Filament\Resources\SurveyResource;
use Filament\Resources\Pages\CreateRecord;

class NewSurvey extends CreateRecord
{
    protected static string $resource = SurveyResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['is_active'] = false;
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }


    protected function handleRecordCreation(array $data): \Illuminate\Database\Eloquent\Model
    {
        // Create the main record.
        $record = parent::handleRecordCreation($data);


        // we assume the json_file is valid by this point.
        // todo: iterate through json questions and put in DB




        return $record;
    }
}
