name: Deploy

on:
  pull_request:
    branches: ['test', 'production']
    types: [closed]
  push:
    branches: ['test', 'production']
  workflow_dispatch:

jobs:
  deploy_to_test:
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH Remote Commands (Test Site)
        uses: appleboy/ssh-action@v0.1.4
        with:
          script: |
            cd public_html/test
            git checkout main -f
            git pull
            git branch -D ${{github.ref_name}}
            git checkout ${{github.ref_name}}
            php artisan migrate --force
            composer update
            npm install
            npm run prod
          host: '207.148.85.120'
          username: 'luminationdev'
          password: ${{ secrets.EDSPARK_DIGITAL_HUB }}

      - run: |
          echo $GITHUB_REF
          echo $GITHUB_PATH
          echo $GITHUB_REF_NAME

  deploy_to_production:
    if: github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH Remote Commands (Production Site)
        uses: appleboy/ssh-action@v0.1.4
        with:
          script: |
            cd public_html/futureSchools/web
            git checkout main -f
            git pull
            git branch -D ${{github.ref_name}}
            git checkout ${{github.ref_name}}
            php artisan migrate --force
            composer update
            npm install
            npm run prod
          host: '207.148.85.120'
          username: 'luminationdev'
          password: ${{ secrets.EDSPARK_DIGITAL_HUB }}

      - run: |
          echo $GITHUB_REF
          echo $GITHUB_PATH
          echo $GITHUB_REF_NAME
